name:     example
version:  0.1.0.0
language: GHC2021

dependencies:
  - base
  - async
  - async-pool
  - bytestring
  - containers
  - io-classes
  - stm
  - hspec

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executable:
  source-dirs: src
  main-is: Main.hs
